### ISSUE TITLE
Giving a Presentation on what we are doing with Drones and ODM 

### ISSUE THREAD

**Issue by LeithHawkins** [OpenDroneMap/presentations#1]
Howdy,  

I have had an abstract picked up for a conference and I am going to be talking about how we use ODM meshlab etc .

Wondered if there  is any specific way I should reference ODM and its creators.  and if there is anything I should be saying other than how freaking awesome it is 👍 

thanks in advance

Leith

**Comment by dakotabenjamin** [comment]
@smathermather can answer that, he's given a few talks before :smile: 

What conference, if I may ask?

**Comment by smathermather** [comment]
Hi @leithhawkins. Main thing is to point folks to all the resources for the project. I usually close with the following:

https://github.com/OpenDroneMap/OpenDroneMap

https://github.com/OpenDroneMap/OpenDroneMap/wiki

https://lists.osgeo.org/cgi-bin/mailman/listinfo/opendronemap-users

https://lists.osgeo.org/cgi-bin/mailman/listinfo/opendronemap-dev

https://gitter.im/OpenDroneMap/OpenDroneMap

https://github.com/OpenDroneMap/OpenDroneMap/wiki/Roadmap

**Comment by LeithHawkins** [comment]
I  am conscious of giving projects like this the credit they deserve.  A small number of people put in significant work so that larger community benefits (I am one of the people riding on the coat tails of this work). 

@dakotabenjamin  it is our New South Wales State Government Cluster conference about enabling spatial technology across our 800 + GIS users. ill make sure to put any links up here.

@smathermather  thanks for the links ill be sure to include them.
